# Generated by Django 4.2.4 on 2023-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='DS_NT',
            field=models.CharField(blank=True, choices=[('Networker', 'Networker'), ('Direct-Seller', 'Direct-Seller')], max_length=15, null=True, verbose_name='Direct or Networker'),
        ),
    ]
