# Generated by Django 4.2.4 on 2023-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_ds_nt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
