# Generated by Django 4.2.4 on 2023-08-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_administrator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
