# Generated by Django 4.2.4 on 2023-08-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_administrator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('access_accounts', 'Can access accounts'), ('access_products', 'Can access products')]},
        ),
    ]
