# Generated by Django 4.2.4 on 2023-08-27 07:38

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('show_price', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_product)),
                ('commission1', models.FloatField(blank=True, max_length=10, null=True)),
                ('commission2', models.FloatField(blank=True, max_length=10, null=True)),
                ('commission3', models.FloatField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
