# Generated by Django 4.2.4 on 2023-08-27 07:51

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_product),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_product),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_product),
        ),
    ]
