# Generated by Django 4.2.4 on 2023-08-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productmodel_image2_productmodel_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='availability',
            field=models.CharField(blank=True, choices=[('In-stock', 'In-stock'), ('Not-available', 'Not-available')], max_length=20, null=True),
        ),
    ]
