# Generated by Django 4.2.4 on 2023-08-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productmodel_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='availability',
            field=models.CharField(choices=[('In-stock', 'In-stock'), ('Not-available', 'Not-available')], default='In-stock', max_length=20),
        ),
    ]
