# Generated by Django 4.2.4 on 2023-08-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_rename_subscriptionlevel_subscriptionlevelmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userearningsmodel',
            name='monthly_earning_limit',
        ),
        migrations.AddField(
            model_name='subscriptionlevelmodel',
            name='monthly_earning_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionlevelmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionlevelmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
