# Generated by Django 4.2.4 on 2023-08-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_userearningsmodel_monthly_earning_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionlevelmodel',
            old_name='monthly_earning_limit',
            new_name='weekly_earning_limit',
        ),
    ]
