# Generated by Django 4.2.4 on 2023-08-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_sellers', '0002_rename_directseller_directsellermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directsellermodel',
            name='ref_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
