# Generated by Django 4.2.4 on 2023-08-28 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direct_sellers', '0003_alter_directsellermodel_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='directsellermodel',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_sellers_referred', to=settings.AUTH_USER_MODEL),
        ),
    ]
