# Generated by Django 4.2.4 on 2023-08-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_sellers', '0004_directsellermodel_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directsellermodel',
            name='referred_by',
        ),
    ]
