# Generated by Django 4.2.4 on 2023-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networker', '0002_networkinguserprofile_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinguserprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
