# Generated by Django 4.2.4 on 2023-08-28 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('networker', '0005_alter_networkinguserprofile_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkinguserprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='networkinguserprofile',
            name='users',
            field=models.ManyToManyField(related_name='networkers_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
