# Generated by Django 4.2.4 on 2023-08-27 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_alter_productmodel_availability'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartItemModel',
        ),
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartModel',
        ),
    ]
